[package]
name = "github-gist-generator"
version = "0.1.0"
authors = ["chaixb <1481569358@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
